---
title: "R Notebook"
output: html_notebook
---

```{r}
libv <- c("ggplot2", "dplyr", "ComplexHeatmap")
sapply(libv, library, character.only = T)
knitr::opts_chunk$set(echo = TRUE)

# load
folder.name <- "13_soptimize_yvary-zvary_dlpfc-cohort1"
file.name <- "df-sopt-result-validation_yvary-zvary_cohort1.rda"
df.res.path <- file.path("deconvo_method-paper", "outputs", folder.name, file.name)
df.res <- get(load(df.res.path))

```

# Dataset summaries

Summarizing the results of validation analyses:

```{r}
summary(df.res$error.neuron)
```

The minimum observed neuron error was: `r min(df.res$erorr.neuron)`

The minimum oberved neuron error by experiment condition was:

```{r}
df.res$experiment.condition <- paste0(df.res$cell.compartment, ";", df.res$library.type)
for(condition in unique(df.res$experiment.condition)){
  message(condition, ":\n")
  print(summary(df.res[df.res$experiment.condition==condition,]$error.neuron))
  message("\n")
}
```

# Heatmap of outcomes, where axes are validation sample by condition

```{r}

```


# Heatmap summaries

```{r}
# s.optimal.diffs

# errors

# adjustments

```
