---
title: "cell-type-qc_cohort1"
author: "Sean Maden"
date: "2023-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("..")
setwd("..")
mae <- get(
  load(
    file.path("outputs", "01_prepare-datasets", "mae_with-rpkm_additional-data_final.rda")))
```

```{r}

#
# MAE.day -- standards for MultiAssayExperiments and similar object class types
#

assay_by_object_list <- function(mae, name.vector, assay.names.catch = c("counts", "Nucleus_Area")){
  #
  # get_assay_name_list
  # 
  assay.name.list <- lapply(name.vector, function(name.iter){
    assays.list.iter <- names(assays(mae[[name.iter]]))
    assays.list.iter[assays.list.iter %in% assay.names.catch]
  })
  names(assay.name.list) <- name.vector 
  return(assay.name.list)
}

get_mae_column_quantity_bygroup <- function(mae, group.variable.name, ...){
  quantity.matrix <- do.call(rbind, lapply(group.name.list, function(group.name){
    mae.iter <- mae.iter
    get_mae_column_quantity(mae.iter, ...)
  }))
  quantity.df <- as.data.frame(quantity.matrix)
  
}

map_column_quantity_options <- function(object, object.label, column.variable.name){
  se.cond <- is(object, "SingleCellExperiment")|is(object, "SummarizedExperiment")|is(object, "ExpressionSet")
  if(se.cond){ # classes containing coldata
    quantity.df <- as.data.frame(table(colData(object)[,column.variable.name]))
    
  } else{
    stop("unrecognized object class.")
  }
  quantity.df$mae.object.name <- object.label
  return(quantity.df)
  return(FALSE)
}

get_mae_column_quantity <- function(mae, object.name.vector = c("sn1.rnaseq", "rnascope.image"), 
                                    column.variable.levels = c("glial", "neuron"),
                                    quantity.type = "counts", column.variable.name = "k2",
                                    return.type = "data.frame"){
  #
  # example:
  # get_mae_column_quantity(mae, c("sn1.rnaseq", "rnascope.image"), c("glial", "neuron"), "counts", "k2")
  # get_mae_column_quantity(mae, c("sn1.rnaseq", "rnascope.image"), c("glial", "neuron"), "proportions", "k2")
  #
  #
  #
  
  # check for valid object names
  object.name.vector <- object.name.vector[object.name.vector %in% names(mae)]
  column.quantity.list <- lapply(object.name.vector, function(object.name){
    quantity.df <- map_column_quantity_options(mae[[object.name]], object.name, column.variable.name)
    quantity.df$quantity.type <- quantity.type
    quantity.df$cell.type.variable.name <- column.variable.name
    return(quantity.df)
  })
  # parse quantity.df options
  if(!is(column.variable.levels, "NULL")){
    column.quantity.list <- lapply(column.quantity.list, function(quantity.df){
      quantity.df[quantity.df[,1] %in% column.variable.levels,]
    })
  }
  if(quantity.type=="proportions"){
    column.quantity.list <- lapply(column.quantity.list, function(quantity.df){
      quantity.df[,2] <- quantity.df[,2]/sum(quantity.df[,2])
      quantity.df
    })
  }
  # parse return options
  if(!return.type=="list"){
    return.object <- as.data.frame(do.call(rbind, column.quantity.list))
    colnames(return.object) <- c("cell.type", "quantity", "mae.object.name", 
                                 "quantity.type", "cell.type.variable.name")
  } else{
    return.object <- column.quantity.list
  }
  return(return.object)
}

quantitydf_to_platformcelltype <- function(quantity.df){
  # gets wide table of platform-celltypes from quantity.df
  platforms <- unique(quantity.df[,3])
  unlist(lapply(platforms, function(platform.iter){
    qdf.iter <- quantity.df[quantity.df[,3]==platform.iter,]
    new.row.iter <- qdf.iter[, 2]
    names(new.row.iter) <- paste0(platform.iter, ";", qdf.iter[,1])
    new.row.iter
  }))
}

get_mae_quantity_bygroup <- function(mae, group.variable.name = "sample.id", 
                                     object.name.vector = c("sn1.rnaseq", "rnascope.image"), 
                                    column.variable.levels = c("glial", "neuron"),
                                    quantity.type = "counts", column.variable.name = "k2",
                                    return.type = "data.frame"){
  #
  # 
  # get_mae_quantity_bygroup(mae, "sample.id")
  #
  #
  
  
  unique.groups <- unique(colData(mae)[,group.variable.name])
  
  list.qdf <- lapply(unique.groups, function(group.iter){
    filter.mae <- colData(mae)[,group.variable.name]==group.iter
    mae.iter <- mae[,filter.mae,]
    qdf.iter <- get_mae_column_quantity(mae.iter, object.name.vector = c("sn1.rnaseq", "rnascope.image"), 
                                    column.variable.levels = c("glial", "neuron"),
                                    quantity.type = "counts", column.variable.name = "k2",
                                    return.type = "data.frame")
    qdf.iter$group.id <- group.iter
    return(qdf.iter)
  })
  
  # bind for tall qdf
  qdf.all <- do.call(rbind, lapply(list.qdf, function(item){item}))
  qdf.all <- as.data.frame(qdf.all)
  
  # get wide df
  qdf.wide <- do.call(rbind, lapply(list.qdf, function(qdf.iter){
    qdf.wide.iter <- quantitydf_to_platformcelltype(qdf.iter)
    c(qdf.wide.iter, unique(qdf.iter$group.id))
  }))
  qdf.wide <- as.data.frame(qdf.wide)
  colnames(qdf.wide)[ncol(qdf.wide)] <- "group.id"
  
  # return
  list.return.all.qdf <- list(qdf.tall = qdf.all, qdf.wide = qdf.wide)
  return(list.return.all.qdf)
}

```

Get quantity data frames.

```{r}
# get sample ids
sample.id.vector <- intersect(unique(mae[[1]]$Sample), unique(mae[[6]]$Sample))
filter.mae <- colData(mae)[,"sample.id"] %in% sample.id.vector
mae.filtered <- mae[,filter.mae,]

# get group quantity df datasets
list.quantity <- get_mae_quantity_bygroup(mae.filtered)
list.proportions <- get_mae_quantity_bygroup(mae.filtered, quantity.type = "proportions")
```

# 1. Check linear model bias distribution

```{r}
library(GGally)

ggpairs(df.lm.quantity[,])



```

```{r}
get_cell_counts <- function(sce.iter, variable){as.data.frame(table(sce.iter[[variable]]))}

get_group_cell_counts <- function(sce, group.variable, celltype.variable){
  group.id.vector <- unique(sce[[group.variable]])
  do.call(rbind, lapply(group.id.vector, function(group.id){
    sce.iter <- sce[,sce[[group.variable]]==group.id]
    counts.iter <- get_cell_counts(sce.iter, celltype.variable)
    counts.iter$group.id <- group.id
    counts.iter
  }))
}

mae_celltype_counts_by_assay <- function(
    mae, 
    assay.name.vector = c("sn1.rnaseq", "rnascope.image"),
    sample.id.variable = "Sample", 
    celltype.variable = "k2",
    cell.types = c("glial", "neuron")){
    #
    # make a table of the following:
    # SAMPLES (ROWS) X ASSAY-CELLTYPE (COLUMNS)
    #
    #
    
    mae <- complete.cases(mae)
  
    # get tall df
    df.tall <- do.call(rbind, lapply(assay.name.vector, function(assay.name.iter){
      df.iter <- get_group_cell_counts(mae[[assay.name.iter]], 
                                       sample.id.variable, celltype.variable)
      df.iter$assay <- assay.name.iter
      return(df.iter)
    }))
    df.tall$ct.assay.label <- paste0(df.tall[,1], ";", df.tall$assay)
    df.tall <- df.tall[df.tall$Var1 %in% cell.types,]
    
    # df.tall.ct.assay
    celltypes.assays <- unique(df.tall$ct.assay.label)
    num.cell.types <- length(cell.types)
    num.groups <- length(unique(df.tall$group.id))
    df.tall.ct.assay <- do.call(cbind, lapply(celltypes.assays, function(celltype.assay){
      df.tall[df.tall[,5]==celltype.assay, 2]
    }))
    df.tall.ct.assay <- as.data.frame(df.tall.ct.assay)
    
    # df.tall.ct
    num.cell.types <- length(cell.types)
    num.entries.tall <- length(which(df.tall[,1]==cell.types[1]))
    df.tall.ct <- do.call(cbind, lapply(cell.types, function(cell.type){
      df.tall[df.tall[,1]==cell.type, 2]
    }))
    df.tall.ct <- as.data.frame(df.tall.ct)
    colnames(df.tall.ct) <- cell.types
    df.tall.ct$assay <- df.tall[df.tall[,1]==cell.types[1],]$assay
    df.tall.ct$group.id <- df.tall[df.tall[,1]==cell.types[1],]$group.id
    
    
    
    
    colnames(df.tall.ct.assay) <- cell.types
    df.tall.ct.assay$assay <- df.tall[df.tall[,1]==cell.types[1],]$assay
    df.tall.ct.assay$group.id <- df.tall[df.tall[,1]==cell.types[1],]$group.id
    
    return(list(df.tall = df.tall, df.tall.ct = df.tall.ct))
}
```



```{r}
df.tall <- mae_celltype_counts_by_assay(mae)[["df.tall"]]
```

# 2. Get PCA

````{r}

mae_pca <- function(){
  library(dplyr)
  library(ggplot2)
  mat.pca <- t(df.tall.ct[,seq(num.cell.types)])
  pca <- prcomp(x = mat.pca)
  
  mat.pca <- df.tall.ct[,seq(num.cell.types)]
  pca <- prcomp(x = mat.pca)
  
  
  # check dim of outputs
  res1 <- prcomp(df.tall.ct[,seq(num.cell.types)])$x
  res2 <- prcomp(t(df.tall.ct[,seq(num.cell.types)]))$x
  
  heatmap(res1)
  
  pca.res <- pca$x %>% as.data.frame()
  ggplot(pca.res, aes(x = PC1, y = PC2)) + geom_point()
  
}

```

# 3. Check PCA relationships across conditions

```{r}
```


