---
title: "Donor variance adjustments"
author: "Sean Maden"
date: "2023-01-19"
output: html_document
---

Show simulation results of donor variance adjustments across low and high donor 
variances.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libv <- c("lute", "ggpubr", "gridExtra")
sapply(libv, library, character.only = TRUE)
```

# Simulate donor data

Get the data.frame of simulated donor signals.

```{r}
df <- donordf <- rand_donor_marker_table(ndonor = 10, gindexv = c(1, 2), 
                              sd.offset.pos = 5, sd.offset.neg = 5)
```

## Compare PCA results

Compare PCA plots of adjusted and unadjusted data.

First, get PCA plots of the unadjusted data.

```{r}
lpca.unadj <- pcaplots_donor(dt = df)
lpca.unadj$pca.bydonortype$scatterplot.pc1.pc2
```

```{r}
df.adj <- donoradj_combat(df, return.type = "donordf")
# get pca for adj signals
lpca.adj <- pcaplots_donor(dt = dfadj)
lpca.adj$pca.bydonortype$scatterplot.pc1.pc2 + ggtitle("Adj. method: combat")
```

# Experiments

Using the `ComBat` method, vary donor variances using offsets of 5 and 100.

```{r}
offsetv <- seq(1e-2,5,1e-2)
lb <- donor_marker_biasexpt(offsetv = offsetv, donor.adj.method = "combat")
```


