---
title: "Donor variance adjustments"
author: "Sean Maden"
date: "2023-01-19"
output: html_document
---

Evaluate the multibrain DLPFC dataset, and repeat donor variance simulations with
appropriate coefficients from observations.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libv <- c("lute", "ggpubr", "gridExtra", "DeconvoBuddies", "SingleCellExperiment")
sapply(libv, library, character.only = TRUE)

# manage paths
# source and save paths
code.dname <- "08_lute-simulations"
proj.dname <- "deconvo_method-paper"
save.dpath <- file.path(proj.dname, "outputs", code.dname)
source.dpath <- file.path(proj.dname, "source")
# single cell experiment
sce.fname <- "sce-mrb_dlpfc.rda"
sce.fpath <- file.path(save.dpath, sce.fname)
# cell type markers
mr.fname <- "markers-k2_db-mr2_sce-dlpfc-mrb.rda"
mr.fpath <- file.path(save.dpath, mr.fname)
# donor markers
mrd.fname <- "markers-donor_db-mr2_sce-dlpfc-mrb.rda"
mrd.fpath <- file.path(save.dpath, mrd.fname)
```

Load the `SingleCellExperiment` object containing multi-region brain DLPFC data,
and marker datasets for cell types and donors, respectively.

```{r}
# get data
sce <- get(load(sce.fpath))
mr <- get(load(mr.fpath))
mrd <- get(load(mrd.fpath))
```

Get top 20 genes per type

```{r}
library(dplyr)
type.variable <- "k2"
ngenes.per.k <- 20
typev <- unique(sce[["k2"]])
ma.top <- do.call(rbind, lapply(typev, function(typei){
    mr %>% filter(cellType.target == typei) %>% arrange(rank_ratio) %>%
      top_n(n = ngenes.per.k)
}))
scef <- sce[ma.top$gene,]
```


Get donor-wise summaries using `lute`.

```{r}
assays(scef)$logcounts <- as.matrix(assays(scef)$logcounts)

di <- sce_groupstat(scef, group.variable = "k2", 
                    summarytype = "colData",
                    assayname = "logcounts", 
                    return.tall = TRUE)

di <- sce_groupstat(scef, group.variable = "k2", 
                    summarytype = "rowData",
                    assayname = "logcounts", 
                    return.tall = TRUE)
```

```{r}
set <- set_from_sce(scef, type.variable = "k2", assayname = "logcounts")
```

```{r}
ma <- as.matrix(assays(scef)$logcounts)
groupv.cd <- scef[["donor"]]
typev.cd <- scef[["k2"]]
ddf <- donordf_from_mexpr(ma, groupv.cd = groupv.cd, typev.cd = typev.cd)

ddf.fname <- "donordf-sce_dlpfc-mrb.rda"
save(ddf, file = ddf.fname)
```

```{r}
ddf.fname <- "donordf-sce_dlpfc-mrb.rda"
ddf <- get(load(ddf.fname))




plot.biasadj <- T
P <- c(0.75, 0.25)
verbose = T
cname.donorsummary <- "donor.mean"
donor.adj.method = "combat"
df <- random_donordf(ndonor = 1, gindexv = c(rep(1, 20), rep(2, 20)),
                     lambda.sdoff.pos = 0, lambda.sdoff.neg = 0)
ktotal <- length(P)
Z <- matrix(df[,"donor1"], ncol = ktotal)
Ypb <- ypb_fromtypes(Z = Z, P = P)

type.indexv <- seq(ktotal)
donor.unadj <- ddf[,cname.donorsummary] # get donor summary datas
lbias <- biasexpt(df = ddf, Ypb = Ypb, P = P, 
                  donor.unadj = donor.unadj,
                  donor.adj.method = donor.adj.method,
                  plot.biasadj = plot.biasadj, verbose = verbose)

```