---
title: "01_halo-cell-sizes_slide-summaries"
author: "Sean Maden"
date: "2023-01-26"
output: html_document
---

```{r}
libv <- c("ggplot2", "ggcorrplot", "gridExtra", "ggpubr")
sapply(libv, library, character.only = T)
```

Compare and summarize HALO size estimates by slide.

# Load data

Use the results files found at: `~./Human_DLFPC_Deconvolution/processed_data/03_HALO/halo_all.Rdata`

```{r}
ha.fpath <- "Human_DLPFC_Deconvolution/processed-data/03_HALO/halo_all.Rdata"
ha <- get(load(ha.fpath))
```

# Process HALO data

Get the k2 and k3 cell types.

```{r}
ha$k2 <- ifelse(ha$cell_type %in% c("Excit", "Inhib"), "neuron", "non-neuron")
ha$k3 <- ifelse(ha$cell_type %in% c("Excit", "Inhib"), "neuron",
                ifelse(ha$cell_type %in% c("Other"), "other", "glial"))
```

# Summary statistics

## Global summaries

```{r}
dfp <- ha
ggbox <- ggplot(dfp, aes(x = SAMPLE_ID, y = Nucleus_Area)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme_bw()
jpeg("ggbox-sample_nucarea-bycell-bycombo_halo-all.jpg", 
     width = 12, height = 6, units = "in", res = 400)
ggbox + facet_wrap(~Combo + cell_type, nrow = 2)
dev.off()
```

```{r}
dfp <- ha
ggbox <- ggplot(dfp, aes(x = Slide, y = Nucleus_Area)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme_bw()
jpeg("ggbox-slide_nucarea-bycell-bycombo_halo-all.jpg", 
     width = 7, height = 4, units = "in", res = 400)
ggbox + facet_wrap(~Combo + cell_type, nrow = 2)
dev.off()
```

## ANOVAs on `Nucleus_Area`

### Basic models

Use `cell_type`

```{r}
av1 <- anova(lm(Nucleus_Area ~ cell_type + Slide + SAMPLE_ID, data = ha))
av1
```

Use `k2`

```{r}
av2 <- anova(lm(Nucleus_Area ~ k2 + Slide + SAMPLE_ID, data = ha))
av2
```

Use `k3`

```{r}
av3 <- anova(lm(Nucleus_Area ~ k3 + Slide + SAMPLE_ID, data = ha))
av3
```

### Complex models

```{r}
av1 <- anova(lm(Nucleus_Area ~ cell_type + Slide + Combo + Position + BrNum, data = ha))
av1
```

```{r}
av2 <- anova(lm(Nucleus_Area ~ k2 + Slide + Combo + Position + BrNum, data = ha))
av2
```

```{r}
av3 <- anova(lm(Nucleus_Area ~ k3 + Slide + Combo + Position + BrNum, data = ha))
av3
```


## Summaries by slide

```{r}
slidev <- unique(ha$SAMPLE_ID)
dfs <- do.call(rbind, lapply(slidev, function(si){
  hai <- ha[ha$SAMPLE_ID==si,]
  ctv <- unique(hai$cell_type)
  total_cells <- nrow(hai)
  dfc <- do.call(rbind, lapply(ctv, function(ci){
    haii <- hai[hai$cell_type==ci,]
    data.frame(slide = si,
               celltype = ci,
               k2 = ifelse(ci %in% c("Inhib|Excit"), "neuron",
                           ifelse(ci %in% c("Other"), "other", "glial")),
               num_cells = nrow(haii),
               fract_cells_slide = nrow(haii)/total_cells,
               nuc_area_median = median(haii$Nucleus_Area),
               nuc_perim_median = median(haii$Nucleus_Perimeter),
               akt3_copies_median = median(haii$AKT3_Copies),
               glare = unique(haii$Glare))
  }))
}))
```

```{r}

lcor <- list()
for(cti in unique(dfs$celltype)){
  dfsi <- dfs[dfs$celltype==cti,]
  mcori <- dfsi[,c("nuc_area_median", "nuc_perim_median", "akt3_copies_median")]
  colnames(mcori) <- c("NuclearArea", "NuclearPerim", "AKT3Copies")
  mcori <- cor(mcori, use = "pairwise.complete.obs", method = "spearman")
  ggcorri <- ggcorrplot(mcori, type = "lower", lab = T, title = cti)
  lcor[[cti]] <- ggcorri
}

lcor[["leg"]] <- get_legend(lcor[[1]])
lcor[["blank"]] <- ggplot() + geom_blank()
for(i in seq(7)){lcor[[i]] <- lcor[[i]] + theme(legend.position = "blank")}



lm <- matrix(c(1,2,3,4,5,6,7,8,9,9), nrow = 2)
jpeg("ggcor-cellsizes_bycelltype_halo-all.jpg", 
     width = 10, height = 6, units = "in", res = 400)
grid.arrange(lcor[[1]], lcor[[2]], lcor[[3]], lcor[[4]], 
             lcor[[5]], lcor[[6]], lcor[[7]], lcor[["blank"]], 
             lcor[["leg"]],
             layout_matrix = lm, nrow = 2)
dev.off()



```

# Figures

```{r}
# ha <- get(load("halo_all.Rdata))
```