---
title: "Pseudobulk s optimize experiment"
author: "Sean Maden"
output:
  pdf_document: default
  html_document: default
---

Results of pseudobulk $S$ optimization experiments.

```{r setup, include=FALSE}
libv <- c("ggplot2", "dplyr")
sapply(libv, library, character.only = T)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
setwd("..")
setwd("..")
list.files()
# setwd("..")
load("./env/04_experiment/01_run_script.RData")
```

# Figure 4A: Heatmaps of neuron error.

View plot.

```{r}
list.plots.dfp1$heatmaps$heatmap1
```

Save plot.

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/04_experiment/fig4a_heatmap.jpg"
jpeg(new.plot.path, width = 5.5, height = 4, units = "in", res = 400)
list.plots.dfp1$heatmaps$heatmap1
dev.off()
```

# Figure 4B: Neuron error deciles and min/max values plots.

View plot. 

```{r}
list.plots.dfp1$heatmaps$heatmap6
```

Save plot.

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/04_experiment/fig4b_deciles.jpg"
jpeg(new.plot.path, width = 6.5, height = 5, units = "in", res = 400)
list.plots.dfp1$heatmaps$heatmap6
dev.off()
```

# Figure 4C: Neuron error by log of S fraction

View plot.

```{r}
list.plots.dfp1$deconvocanos$cano2
```

Save plot.

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/04_experiment/fig4c_errorfraction.jpg"
jpeg(new.plot.path, width = 5.5, height = 4, units = "in", res = 400)
list.plots.dfp1$deconvocanos$cano2
dev.off()
```

# Session info

```{r}
sessionInfo()
```
