---
title: "nmarker-by-bias_nnls-music_dlpfc-cohort2"
author: "Sean Maden"
date: "2023-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libv <- c("lute", "here", "dplyr", "ggplot2", "reshape2", "ggforce")
sapply(libv, library, character.only = T)
```

Load sce data

```{r}
# load mrb dlpfc cohort2
sce.filename <- "sce-mrb_dlpfc.rda"
base.path <- file.path("outputs", "01_prepare-datasets")
sce.path <- here(base.path, sce.filename)
sce <- get(load(sce.path))
```

# Get results

Set experiment parameters.

```{r}
# params
deconvo.algo.vector <- "nnls"
assay.name <- "logcounts"
celltype.variable <- "k2"
nmarkers.vector <- c(10, 20, 30, 40, 50, 
                     100, 200, 300, 400, 500, 
                     1000, 2000, 3000, 4000, 5000)
donor.id.variable <- "donor"
unique.donors <- unique(sce[[donor.id.variable]])
# get true proportions for pseudobulk
p.true <- do.call(cbind, lapply(unique.donors, function(donor.id){
  scef <- sce[,sce[[donor.id.variable]]==donor.id]
  scef[[donor.id.variable]] <- droplevels(scef[[donor.id.variable]])
  table(scef$k2, scef$donor) %>% prop.table()
})) 
colnames(p.true) <- unique.donors
# get pseudobulk
ypb <- do.call(cbind, lapply(unique.donors, function(donor.id){
  ypb_from_sce(sce[,sce$donor==donor.id], "logcounts", "k2", 
               S = c("glial" = 3, "neuron" = 10)) %>% as.matrix()
}))
colnames(ypb) <- unique.donors

# helper functions
get_experiment_results <- function(sce, p.true, ypb, deconvo.algo, 
                                  nmarkers.vector, unique.donors, 
                                  donor.id.variable){
  df.res <- do.call(rbind, lapply(deconvo.algo, function(algo){
  do.call(rbind, lapply(nmarkers.vector, function(nmarkers){
    dfi <- do.call(rbind, lapply(unique.donors, function(donor.id){
        resi <- lute(sce[,sce[[donor.id.variable]]==donor.id], y = ypb[,donor.id,drop=F], 
             celltype.variable = celltype.variable, assay.name = assay.name,
             markers.per.type = nmarkers, deconvolution.algorithm = algo)
        resi <- resi[["deconvolution.results"]]@predictions.table
        colnames(resi) <- paste0(colnames(resi), ".pred")
        resi$glial.true <- p.true[,donor.id]["glial"]
        resi$neuron.true <- p.true[,donor.id]["neuron"]
        resi$bias.neuron <- resi$neuron.true-resi$neuron.pred
        resi$bias.glial <- resi$glial.true-resi$glial.pred
        resi
      }))
    dfi$nmarker <- nmarkers
    dfi$donor <- unique.donors
    dfi$deconvolution.algorithm <- algo
    dfi
    }))
  }))
  df.res
}
```

Get the combined results.

```{r}
df.res <- get_experiment_results(sce, p.true, ypb, deconvo.algo.vector, 
                                 nmarkers.vector, unique.donors, donor.id.variable)
```

# Plot results

Cell counts by type.

```{r}
dfp <- melt(p.true) %>% as.data.frame()
colnames(dfp) <- c("cell_type", "donor", "proportion")

ggplot(dfp, aes(x = donor, y = proportion, fill = cell_type)) + 
  geom_bar(position = "stack", stat = "identity") + theme_bw()
```

Bias versus number of markers.

```{r}
ggplot(df.res, aes(x = nmarker, y = bias.neuron, 
                   shape = donor, lty = donor, color = donor)) +
  geom_line() + geom_point() + theme_bw() + geom_hline(yintercept = 0) +
  facet_zoom(xlim = c(10, 500)) + xlab("Markers per cell type (G/K)") + 
  ylab("Neuron proportion (P_pred - P_true)")
```