---
title: "S optimization summaries -- pseudobulk k2"
author: "Sean Maden"
date: "2023-07-31"
output: html_document
---

Shows optimization summaries for pseuobulk studies of K2.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("..")
base.path <- file.path("deconvo_method-paper", "code", "02_pseudobulk-predictions")
script.name <- "01_only-k2_lute-pseudobulk-experiment_dlpfc-cohort1.R"
source(file.path(base.path, script.name))
```

# get some S series

```{r}
s.glial.series <- seq(1,100,1)
s.neuron.series <- rev(s.glial.series)
dfs.series <- do.call(rbind, lapply(seq(length(s.glial.series)), function(index1){
  do.call(rbind, lapply(s.neuron.series, function(index2){
    c("glial" = s.glial.series[index1], "neuron" = s.neuron.series[index2])
  }))
})) %>% as.data.frame()
plot(dfs.series$glial, dfs.series$neuron)
```

# optimize one sample

```{r}
# check for results file before build
base.path <- file.path("outputs", "11_s-optimize-noteboook")
save.name <- paste0("df-s-optimize-results_numiter-",nrow(dfs.series),
                    "_1-sample-dlpfc-cohort1.rda")
save.path <- file.path(base.path, save.name)
# set sample id
sample.id <- "Br2720_mid"
  sce.iter <- sce.k2[,sce.k2$Sample==sample.id]
if(!file.exists(save.path)){
  df.res <- do.call(rbind, lapply(seq(nrow(dfs.series)), function(index){
    s.iter <- dfs.series[index,] %>% as.vector() %>% unlist()
    res <- get_ypb_experiment_series(sce.iter, sample.id.variable = "Sample", 
                                   celltype.variable = "k2", assay.name = "logcounts",
                                   s.vector = s.iter, algorithm.name = "nnls",
                                   return.dimensions = "wide")
    res$bias.true.pred.withscale <- res$neuron.true.withscale-res$neuron.pred.withscale
    res$s.glial <- s.iter["glial"]
    res$s.neuron <- s.iter["neuron"]
    res
  }))
  df.res$sample.id <- sample.id
  # save
  save(df.res, file = save.path)
} else{
  df.res <- get(load(save.path))
}
```

Plot bias value in 3 dimensions.

```{r}
ggplot(df.res, aes(s.neuron, s.glial)) + theme_bw() +
  geom_raster(aes(fill = bias.true.pred.withscale)) +
  scale_fill_gradientn(colours = rainbow(5))
```

Plot absolute bias in 3 dimensions.

```{r}
df.res$abs.bias <- abs(df.res$bias.true.pred.withscale)
ggplot(df.res, aes(s.neuron, s.glial)) + theme_bw() +
  geom_raster(aes(fill = abs.bias)) +
  scale_fill_gradientn(colors = rainbow(5))
```

Interactive 3d surface plot.

```{r}
library(plotly)
library(reshape2)
matrix.z <- acast(dfp, s.neuron~s.glial, value.var="bias.true.pred.withscale")
fig <- plot_ly(x = dfp$s.neuron, y = dfp$s.glial, 
               z = matrix.z) %>% add_surface()
fig
```
3d scatterplot

```{r}
fig <- plot_ly(
  dfp, x = ~s.neuron, y = ~s.glial, z = ~bias.true.pred.withscale, 
  color = ~bias.true.pred.withscale)
fig <- fig %>% add_markers()
fig
```


