---
title: "S optimize bias, all samples, cohort1"
author: "Sean Maden"
date: "2023-08-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libv <- c("ggplot2")
sapply(libv, library, character.only = T)
```

# load results

```{r}
setwd("..")
load.filename <- "df-result_s-opt-bias_cohort1.rda"
load.path <- file.path("deconvo_method-paper", "outputs", "11_soptimize-pbfit-bias_dlpfc-cohort1", load.filename)
df.res <- get(load(load.path))
df.res$abs.bias.neuron <- abs(df.res$bias.neuron.true.pred)
```

# plot results

```{r}
ggplot(df.res, aes(x = neuron, y = bias.neuron.true.pred, color = sample.id)) + 
  geom_point(alpha = 0.2) + theme_bw() + facet_wrap(~sample.id) + geom_hline(yintercept = 0)

ggplot(df.res, aes(x = neuron, y = bias.neuron.true.pred, color = sample.id)) + 
  theme_bw() + facet_wrap(~sample.id) + geom_hline(yintercept = 0) +
  geom_smooth(method = "glm", se = T)

ggplot(df.res, aes(x = neuron, y = bias.neuron.true.pred, color = sample.id)) + 
  theme_bw() + geom_smooth(method = "glm", se = T) + geom_hline(yintercept = 0)

ggplot(df.res, aes(x = neuron, y = bias.glial.true.pred, color = sample.id)) + 
  theme_bw() + geom_smooth(method = "glm", se = T) + geom_hline(yintercept = 0)
```

heatmap

```{r}
ggplot(df.res, aes(x = glial, y = neuron)) + theme_bw() +
  geom_raster(aes(fill = bias.neuron.true.pred)) +
  scale_fill_gradientn(colours = rainbow(5)) + facet_wrap(~sample.id) + 
  geom_vline(xintercept = 3) + geom_hline(yintercept = 10)

ggplot(df.res, aes(x = glial, y = neuron)) + theme_bw() +
  geom_raster(aes(fill = abs.bias.neuron)) +
  scale_fill_gradientn(colours = rainbow(5)) + 
  facet_wrap(~sample.id) +
  geom_vline(xintercept = 3) + geom_hline(yintercept = 10) +
  geom_abline(slope = 1, intercept = 0)

```

Plots appending linear models

```{r}
```
