---
title: "00_debug_vignette"
author: "Sean Maden"
date: '2022-10-17'
output: html_document
---

Vignette for debugging `pb_methods` functions.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load data

```{r}
library(here)
# library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
message("here: ", here())
proj.dpath <- "deconvo_method-paper"
# source methods
source.dpath <- file.path("deconvo_method-paper",
                          "source")
source.fnv <- c("pb_methods", 
                "z_transformations")
for(fni in source.fnv){
  source(
    file.path(here(), 
              source.dpath, 
              paste0(fni, ".R")))}
lz.fname <- "lz_s-rescale-k4_dlpfc-ro1.rda"
lz.fpath <- file.path(proj.dpath, 
                      "outputs/03_test-stransform", 
                      lz.fname)
lz <- get(load(file.path(here(), lz.fpath)))
sef.fname <- "sef-markers_ct-treg_stransform-expt_dlpfc-ro1.rda"
sef.fpath <- file.path(proj.dpath, 
                      "outputs/03_test-stransform", 
                      sef.fname)
sef <- get(load(file.path(here(), sef.fpath)))
lexpt <- lz["z.final"]
```

# Debug report and pi expt functions

```{r}
scalei <- 1000
nk <- 4; nj <- 10
datv <- rep(c(10,10,5,5), nj)
```

```{r}
lpb <- get_pb_experiment(lz = lexpt, 
                         sef = sef, 
                         datv = datv, 
                         scale.range = scalei, 
                         ctvarname = "celltype.treg", 
                         plot.results = FALSE, 
                         method.str = "nnls", 
                         seed.num = si,
                         get.results = F)
```
```{r}
get_pi_est(z.data = lexpt[[1]], y.data = lpb$lpb$y_data_pb)
```
