---
title: "Dataset summaries, sample source IDs"
author: "Sean Maden"
date: "2023-10-13"
output:
  pdf_document: default
  html_document: default
---

Sample source IDs dataset summaries.

```{r setup, include=FALSE}
libv <- c("MultiAssayExperiment", "SummarizedExperiment")
sapply(libv, library, character.only = TRUE)
knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
list.files()
load('./env/02_summarize_mae/01_data_summaries_script.RData')
```

# FORMAT

```{r}
dfFilterAll <- df.filter.all
maeAll <- mae.all
snRNASeq <- maeAll[["snrnaseq.k2.all"]]
```

# snRNASeq Summaries

```{r}
nuSummaryTable <- function(snRNASeq){
  # donors map donors
    numDonors.snRNASeq <- unique(snRNASeq$BrNum) |> length()
  numSamples.snRNASeq <- unique(snRNASeq$SAMPLE_ID) |> length()
  
  # fract region
  # CHECK/CONVINCE
  # as.data.frame(table(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))[,1]
  #
  fractRegionByDonor.snRNAseq <- 
    snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos |> 
    list() |>
    sapply(function(item){table(item)}) |> 
    as.data.frame() |> sapply(function(value){value/numDonors.snRNASeq}) |>
    as.vector()
  
  # names fract region
  # CHECK/CONVINCE
  # names(table(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))==unique(
  # snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos)[
  #  order(unique(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))]
  #
  #
  namesFractRegion <- unique(
    snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos)[
    order(unique(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))]
  namesFractRegion <- paste0(namesFractRegion, "Fraction")
  
  # fractRegionByDonor.snRNAseq
  newSummaryTablePre <- data.frame(
    numDonors.snRNASeq,
    numSamples.snRNASeq
  )
  newSummaryTablePre <- fractRegionByDonor.snRNAseq |> 
    matrix(nrow=1) |> 
    cbind(newSummaryTablePre)
  # out
  newSummaryTableOut <- newSummaryTablePre[,c(4,5,1,2,3)]
  #colnames(newSummaryTableOut)[seq(3,5)] <- unique(
  #  snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos)[
  #    order(
  #      unique(
  #        snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))]
  colnames(newSummaryTableOut)[seq(3,5)] <- namesFractRegion
  newSummaryTableOut
    
  return(newSummaryTableOut)
}

nuSummaryTable(snRNASeq)
```

```{r}
nuSummaryTable2 <- function(snRNASeq){
  # donors map samples
  numSamples.snRNASeq <- unique(snRNASeq$BrNum) |> length()
  
  # fract region
  # CHECK/CONVINCE
  # as.data.frame(table(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))[,1]
  #
  fractRegionBySample.snRNAseq <- 
    snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos |> 
    list() |>
    sapply(function(item){table(item)}) |> 
    as.data.frame() |> sapply(function(value){value/numSamples.snRNASeq}) |>
    as.vector()
  
  # names fract region
  # CHECK/CONVINCE
  # names(table(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))==unique(
  # snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos)[
  #  order(unique(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))]
  #
  #
  namesFractRegion <- unique(
    snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos)[
    order(unique(snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))]
  namesFractRegion <- paste0(namesFractRegion, "Fraction")
  
  # fractSexByDonor
  # CHECK/CONVINCE
  # as.data.frame(table(snRNASeq[,!duplicated(snRNASeq$BrNum)]$sex))[,1]
  fractSexBySample.snRNASeq <- 
    snRNASeq[,!duplicated(snRNASeq$BrNum)]$sex |> 
    list() |>
    sapply(function(item){table(item)}) |> 
    as.data.frame() |> 
    sapply(function(value){value/numSamples.snRNASeq}) |>
    as.vector()
  # names fract sex
  namesFractSex.snRNASeq <- unique(
    snRNASeq[,!duplicated(snRNASeq$BrNum)]$sex)
  
  # output table
  newSummaryTablePre <- data.frame(
    numSamples.snRNASeq
  )
  newSummaryTablePre <- fractRegionBySample.snRNAseq |> 
    matrix(nrow=1) |> 
    cbind(newSummaryTablePre)
  newSummaryTablePre <- fractSexBySample.snRNASeq |>
    matrix(nrow=1) |>
    cbind(newSummaryTablePre)
  # out
  # bind
  newSummaryTableOut <- newSummaryTablePre[,c(5,6,1,2,3,4)]
  
  newSummaryTablePre[,c(4,5,1,2,3)]
  #colnames(newSummaryTableOut)[seq(3,5)] <- unique(
  #  snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos)[
  #    order(
  #      unique(
  #        snRNASeq[,!duplicated(snRNASeq$BrNum)]$pos))]
  colnames(newSummaryTableOut)[seq(3,5)] <- namesFractRegion
  newSummaryTableOut
    
  return(newSummaryTableOut)
}

nuSummaryTable2snRNASeq <- nuSummaryTable2(snRNASeq)

```

Nuclei summaries

```{r}

snRNASeq$BrNum |> table() |> as.data.frame()

# this should work, could explain pipes issues 
colData(snRNASeq) |> dplyr::group_by(BrNum) |> dplyr::summarise(median = median(count))

group_by(colData(snRNASeq), BrNum)

library(dplyr)

colData(snRNASeq) %>% as_tibble() %>% group_by(BrNum) %>% summarise(median = median(count))

# get the median number of columns in colData(snRNASeq) by BrNum
# does not work colData(snRNASeq) %>% as_tibble() %>% group_by(BrNum) %>% summarise(median = median(count))
# does not work counts(snRNASeq) |> colSums() |> summary()
#
#
#
#
# does not work counts(snRNASeq) |> aggregate(., by = list(BrNum = snRNASeq$BrNum), FUN = sum) |> summary()
#
#
#
#
#

# get function for dplyr median summary by group


# search internet for dplyr median summary by group
# search internet for dplyr median summary by group

counts(snRNASeq) |> dplyr::summarise(median = median(count))

# get median columns snRNASeq
counts(snRNASeq) |> colSums() |> summary()

# get median columns snRNASeq by BrNum
counts(snRNASeq) |> dplyr::group_by(BrNum) |> dplyr::summarise(median = median(count))

```

## save

```{r}
setwd("..")
setwd("..")
write.csv(nuSummaryTable2snRNASeq, file = "./outputs/02_summarize_mae/TABLE_S1.csv", row.names = FALSE)
```

# MAE Summaries

# Inspect tables

Filters comparison

```{r}
dfFilterAll <- df.filter.all
dfFilterAll
```

# Inspect sample IDs

Pre-filter sample IDs

```{r}
message("all")
unique(mae.all@sampleMap$primary)
message("snrnaseq")
unique(mae.all[[1]][["Sample"]])
message("rnascope")
unique(mae.all[["sce.img"]]$Sample)
```

Post-filter sample IDs.

```{r}
message("all")
unique(mae.filter@sampleMap$primary)
message("snrnaseq")
unique(mae.filter[[1]][["Sample"]])
message("rnascope")
unique(mae.filter[["sce.img"]]$Sample)
```

# Sample summaries plots

## Upset plots

```{r}
mae.upset <- mae.filter[,,c(1,4,6)]
names(mae.upset) <- c("snRNAseq", "bulk RNAseq", "RNAscope")
# training
filter.train <- colData(mae.upset)$sample.id %in% sample.id.train
mae.upset.train <- mae.upset[,filter.train,]
# validation
filter.validate <- colData(mae.upset)$sample.id %in% sample.id.validate
mae.upset.validate <- mae.upset[,filter.validate,]
```

All samples

```{r}
setwd("..")
setwd("..")
jpeg("./figures/02_summarize_mae/figs_upset-mae-all.jpg", 
     width = 4, height = 2.5, units = "in", res = 400)
upsetSamples(mae.upset)
dev.off()
```

Training 

```{r}
setwd("..")
setwd("..")
jpeg("./figures/02_summarize_mae/figs_upset-mae-train.jpg", 
     width = 4, height = 2.5, units = "in", res = 400)
upsetSamples(mae.upset.train)
dev.off()
```

Validation 

```{r}
setwd("..")
setwd("..")
jpeg("./figures/02_summarize_mae/figs_upset-mae-validate.jpg", 
     width = 4, height = 2.5, units = "in", res = 400)
upsetSamples(mae.upset.validate)
dev.off()
```
# Sample quality summaries

```{r}
sample.id.train
```

Bulk

```{r}
bulk <- mae[["bulk.rnaseq"]]

# counts summary
assays(bulk)[["counts"]] |> colSums() |> summary()

# count zeros
apply(assays(bulk)[["counts"]],2,function(ci){length(ci[ci==0])}) |> summary()

length(intersect(bulk$batch.id2, sample.id.train)) 
length(intersect(bulk$batch.id2, sample.id.validate))

bf <- bulk[bulk$library_prep=="Bulk",]
length(intersect(bf$batch.id2, sample.id.train)) 
length(intersect(bf$batch.id2, sample.id.validate))

bf <- bulk[bulk$library_prep=="Cyto",]
length(intersect(bf$batch.id2, sample.id.train)) 
length(intersect(bf$batch.id2, sample.id.validate))

bf <- bulk[bulk$library_prep=="Nuc",]
length(intersect(bf$batch.id2, sample.id.train)) 
length(intersect(bf$batch.id2, sample.id.validate))

bf <- bulk[bulk$library_type=="polyA",]
length(intersect(bf$batch.id2, sample.id.train)) 
length(intersect(bf$batch.id2, sample.id.validate))

bf <- bulk[bulk$library_type=="RiboZeroGold",]
length(intersect(bf$batch.id2, sample.id.train)) 
length(intersect(bf$batch.id2, sample.id.validate))
```

snRNA-seq

```{r}
sce <- rbind(mae[["snrnaseq.k2.all"]], mae[["snrnaseq.k2.all"]])

# counts summary
assays(sce)[["counts"]] |> colSums() |> summary()

# count zeros
apply(assays(bulk)[["counts"]],2,function(ci){length(ci[ci==0])}) |> summary()

```

RNAscope

```{r}
img <- mae[["sce.img"]]
length(unique(img$Sample))
length(intersect(img$Sample, sample.id.train))
length(intersect(img$Sample, sample.id.validate))
```

# Summaries

```{r}

```

# Session info

```{r}
sessionInfo()
```

