---
title: "Pseudobulk k2 with and without cell size rescaling, cohort1"
author: "Sean Maden"
date: "2023-09-17"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
libv <- c("here", "nlme", "lute", "ggplot2", "gridExtra", 
          "dplyr", "ggforce", "MultiAssayExperiment", "SingleCellExperiment")
sapply(libv, library, character.only = TRUE)
knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
list.files()
load("env/01_multipanel/01_pseudobulk_script.RData")
```

# Plots

```{r}

plotData <- rbind(dfp.tall.c1.k2, dfp.tall.c2.k2) |> as.data.frame()

plotK2.c1Scatter.neuron <- ggplot(dfp.tall.c1.k2, aes(x = neuron.true, y = neuron.pred)) + geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1)) + facet_wrap(~type) + geom_abline(slope = 1) +
  xlab("True") + ylab("Predicted") + ggtitle("Cohort1\nNeuron") + xlim(0,1) + ylim(0,1)
plotK2.c2Scatter.neuron <- ggplot(dfp.tall.c2.k2, aes(x = neuron.true, y = neuron.pred)) + geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1)) + facet_wrap(~type) + geom_abline(slope = 1) +
  xlab("True") + ylab("Predicted") + ggtitle("Cohort2\n") + xlim(0,1) + ylim(0,1)
plotK2.c1Scatter.glial <- ggplot(dfp.tall.c1.k2, aes(x = glial.true, y = glial.pred)) + geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1)) + facet_wrap(~type) + geom_abline(slope = 1) +
  xlab("True") + ylab("Predicted") + ggtitle("Glial") + xlim(0,1) + ylim(0,1)
plotK2.c2Scatter.glial <- ggplot(dfp.tall.c2.k2, aes(x = glial.true, y = glial.pred)) + geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1)) + facet_wrap(~type) + geom_abline(slope = 1) +
  xlab("True") + ylab("Predicted") + ggtitle("") + xlim(0,1) + ylim(0,1)

plotK2.c1box.neuron <- 
  ggplot(dfp.tall.c1.k2, aes(x = type, y = neuron.abs.error)) +
  geom_boxplot(color="cyan") + geom_jitter(alpha = 0.5) + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1), axis.title.x = element_blank()) + xlab("Type") + 
  ylab("Error") + ggtitle("\n")
plotK2.c2box.neuron <- 
  ggplot(dfp.tall.c2.k2, aes(x = type, y = neuron.abs.error)) +
  geom_boxplot(color="cyan") + geom_jitter(alpha = 0.5) + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1), axis.title.x = element_blank()) + xlab("Type") + 
  ylab("Error") + ggtitle("\n")
plotK2.c1box.glial <- 
  ggplot(dfp.tall.c1.k2, aes(x = type, y = glial.abs.error)) +
  geom_boxplot(color="cyan") + geom_jitter(alpha = 0.5) + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1)) + xlab("Type") + 
  ylab("Error") + ggtitle("")
plotK2.c2box.glial <- 
  ggplot(dfp.tall.c2.k2, aes(x = type, y = glial.abs.error)) +
  geom_boxplot(color="cyan") + geom_jitter(alpha = 0.5) + theme_bw() + theme(axis.text.x = element_text(angle = 45,hjust=1)) + xlab("Type") + 
  ylab("Error") + ggtitle("")

```

```{r}

layoutMatrix <- matrix(c(rep(seq(8), each = 2)), nrow = 2, byrow=T)

grid.arrange(plotK2.c1Scatter.neuron,
             plotK2.c1box.neuron,
             plotK2.c2Scatter.neuron,
             plotK2.c2box.neuron,
             plotK2.c1Scatter.glial,
             plotK2.c1box.glial,
             plotK2.c2Scatter.glial,
             plotK2.c2box.glial,
             layout_matrix = layoutMatrix)

```
Save

```{r}

jpeg("./figures/01_multipanel/pseudobulk-k2-2cohort_multi.jpg", width = 8, height = 4, units = "in", res = 400)

grid.arrange(plotK2.c1Scatter.neuron,
             plotK2.c1box.neuron,
             plotK2.c2Scatter.neuron,
             plotK2.c2box.neuron,
             plotK2.c1Scatter.glial,
             plotK2.c1box.glial,
             plotK2.c2Scatter.glial,
             plotK2.c2box.glial,
             layout_matrix = layoutMatrix)

dev.off()

```

# Save

```{r}
```

# Session info

```{r}
sessionInfo()
```