---
title: "Deconvolution with ABIS-seq"
author: "Sean Maden"
date: "2023-10-17"
output: html_document
---

```{r setup, include=FALSE}
libv <- c("ggplot2")
sapply(libv, library, character.only = TRUE)
knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
load("./env/02_abisseq/01_abisseq_script.RData")
```

Compare deconvolution results, with versus without scaling on cell size scale 
factors, using the ABIS-seq reference.

# Summaries

Flow cytometry proportions

```{r}
message("original:")
summary(df.wide$true.prop.mean.flow.cyto)
message("format:")
summary(df.wide$true.prop.mean.flow.cyto.format)
```

Predicted proportions

```{r}
message("scaled")
summary(df.tall$mean.scaled)
message("unscaled")
summary(df.tall$mean.unscaled)
```


# Plot

View 

```{r}
ggplot(df.wide, aes(x = true.prop.mean.flow.cyto.format, y = mean, color = cell.type)) + 
  geom_point(size = 4, alpha = 0.5) + geom_abline(slope = 1, intercept = 0) +
  theme() + facet_wrap(~type) + xlab("True") + ylab("Predicted")
```
Boxplots with jittered points.

```{r}
ggplot(df.wide, aes(x = type, y = error.flow.cyto, color = cell.type)) +
  geom_jitter(alpha = 0.5, size = 4) + geom_boxplot(alpha = 0, color = "cyan") +
  theme() + xlab("Error") + ylab("Type")
```

Save

```{r}
```

# Session info

```{r}
sessionInfo()
```

