---
title: "Results of S optimization in all real bulk RNA-seq training samples"
author: "Sean Maden"
date: "2023-09-20"
output:
  pdf_document: default
  html_document: default
---

$S$-optimization experiments were performed on a subset of all real bulk RNA-seq training samples from multiple preparation conditions.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
libv <- c("dplyr", "ggplot2")
sapply(libv, library, character.only = TRUE)
```

```{r}
setwd("..")
setwd("..")
load("./outputs/06_estimate/list_results_train_plot.rda")
```

```{r}
# format plot data
dfp <- list.dfp$dfp.tall
dfp <- dfp[dfp$crossvalidation=="train",]
# dfp$median <- format(dfp$median, scientific = TRUE, digits = 6)
```

# Supplemental Figure 2A: Median error by search step in all real bulk RNA-seq training samples

View plot.

```{r}
new.plot <- ggplot(dfp, aes(x = dfs.num.steps, y = median)) +
  geom_point() + geom_line() + ylab("Median error (neuron)") +
  xlab("Step count")

new.plot
```

Save plot.

```{r}
setwd("..")
setwd("..")
new.jpg.path <- "./figures/06_estimate/figs2_error_steps_train_all.jpeg"
jpeg(new.jpg.path, width = 5, height = 4, units = "in", res = 400)
new.plot; dev.off()
```

# Session info

```{r}
sessionInfo()
```

