---
title: "S optimization on a single real bulk RNA-seq sample using convergent search"
author: "Sean Maden"
date: "2023-09-27"
output:
  pdf_document: default
  html_document: default
---

Demonstrates convergent search strategy for a single real bulk RNA-seq sample.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
libv <- c("ggplot2", "gridExtra")
sapply(libv, library, character.only = T)
setwd("..")
setwd("..")
load("./env/06_estimate/01_run_bulk_1sample_convergent_script.RData")
```

```{r}
# format plot data
dfp <- list.res.plots$dfp
dfp.tall <- rbind(
  data.frame(value = dfp$time.elapsed, variable = rep("time.elapsed", nrow(dfp))),
  data.frame(value = dfp$min.error.neuron, variable = rep("min.error.neuron", nrow(dfp))),
  data.frame(value = dfp$s.opt.neuron, variable = rep("s.opt.neuron", nrow(dfp))),
  data.frame(value = dfp$s.opt.glial, variable = rep("s.opt.glial", nrow(dfp)))
)
dfp.tall <- as.data.frame(dfp.tall)
dfp.tall$run.iteration <- rep(seq(4), nrow(dfp*4))

ggplot(dfp.tall, aes(x = run.iteration, y = value)) + 
  geom_point() + geom_line() + facet_wrap(~variable, ncol = 1)
```

# Supplemental Figure 2B

View plot.

```{r}
new.plot1 <- list.res.plots$min.error.neuron + 
  theme(axis.text.x = element_blank(), axis.title.x = element_blank()) +
  ylab("Min. error\n(neuron)")
new.plot2 <- list.res.plots$time.elapsed + 
  theme(axis.text.x = element_blank(), axis.title.x = element_blank()) +
  ylab("Time elapsed\n(seconds)")
new.plot3 <- list.res.plots$s.optimal.neuron + 
  theme(axis.text.x = element_blank(), axis.title.x = element_blank()) +
  ylab("S optimal\n(neuron)")
new.plot4 <- list.res.plots$s.optimal.glial +
  ylab("S optimal\n(glial)")

grid.arrange(new.plot1, new.plot2, new.plot3, new.plot4, ncol = 1)
```

Save plot.

```{r}
setwd("..")
setwd("..")
jpeg("./figures/06_estimate/figs_1sample_sopt_iterations.jpg", 
     width = 3, height = 5, units = "in", res = 400)
grid.arrange(new.plot1, new.plot2, new.plot3, new.plot4, ncol = 1)
dev.off()
```

# Session info

```{r}
sessionInfo()
```
