---
title: "Results of S optimization in real bulk RNA-seq training sample subset"
author: "Sean Maden"
date: "2023-09-20"
output:
  pdf_document: default
  html_document: default
---

$S$-optimization experiments were performed on a subset of all real bulk RNA-seq training samples from multiple preparation conditions.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
libv <- c("dplyr", "ggplot2")
sapply(libv, library, character.only = TRUE)
```

```{r}
setwd("..")
setwd("..")
load("./outputs/06_estimate/02_run_limited_resolution_script.RData")
```

```{r}
# format plot data
# dfp <- list.dfp$dfp.tall
# dfp <- dfp[dfp$crossvalidation=="train",]
# dfp$median <- format(dfp$median, scientific = TRUE, digits = 6)
```

# Supplemental Figure: Median error by search step in real bulk RNA-seq training subset

View plot.

```{r}

new.plot1 <- ggplot(dfp, aes(x = steps, y = median.train)) +
  geom_point() + geom_line() + ylab("Median error (neuron)") +
  xlab("Step count")

new.plot2 <- ggplot(dfp, aes(x = steps, y = min.train)) +
  geom_point() + geom_line() + ylab("Min. error (neuron)") +
  xlab("Step count")

new.plot3 <- ggplot(dfp, aes(x = min.train, y = min.val, color = steps)) +
  geom_point() + geom_abline(slope = 1, intercept = 0)

new.plot4 <- ggplot(dfp, aes(x = sd.train, y = sd.val, color = steps)) +
  geom_point() + geom_abline(slope = 1, intercept = 0) +
  xlim(0, 0.3) + ylim(0, 0.3)

new.plot1

new.plot2

new.plot3

new.plot4

```

```{r}

new.plot <- ggplot(dfp.tall, aes(x = dfs.num.steps, y = sd, color = crossvalidation)) + 
  geom_point() + geom_line() 

new.plot

new.plot2 <- ggplot(dfp.tall, aes(x = dfs.num.steps, y = median, color = crossvalidation)) + 
  geom_point() + geom_line() 

new.plot2

new.plot3 <- ggplot(dfp.tall, aes(x = dfs.num.steps, y = min, color = crossvalidation)) + 
  geom_point() + geom_line() 

new.plot3

```

Save plot.

```{r}
setwd("..")
setwd("..")
new.jpg.path <- "./figures/06_estimate/figs_error_steps_train_subset.jpeg"
jpeg(new.jpg.path, width = 5, height = 4, units = "in", res = 400)
new.plot; dev.off()
```

# Session info

```{r}
sessionInfo()
```
