---
title: "01_run"
author: "Sean Maden"
date: "2023-10-02"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
libv <- c("ggplot2", "reshape2")
sapply(libv, library, character.only = TRUE)

knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
load("./env/09_quality/01_run_script.RData")


```

# Quality summaries

Plots and tables

```{r}


xaxis.label <- paste0("Samples (N = ", length(unique(df.conf$sample.id)), ")")
yaxis.label <- paste0("Combos (N = ", length(unique(df.conf$combo)), ")")

ggplot(df.conf, aes(x = sample.id, y = combo, fill = confidence)) + 
  geom_tile(color = "black") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab(xaxis.label) +
  ylab(yaxis.label)


```

As single row, by slide

```{r}





plot.variable.name <- "is.high.and.middle"

df.newplot <- dfp.tall[dfp.tall$type=="noscale",]

plot.variable.name


df.newplot[,plot.variable.name] == 

df.newplot[is.na(df.newplot),]

xaxis.label <- paste0(
  "Samples (N = ", 
  length(unique(df.newplot$sample.id)), 
  ")")
yaxis.label <- paste0(
  "is.high.and.middle (states = ",
  length(unique(df.newplot$is.high.and.middle)),
  ")")

ggplot(df.newplot, 
       aes(x = sample.id, y = "", 
           fill = is.high.and.middle)) + 
  geom_tile(color = "black") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab(xaxis.label) +
  ylab(yaxis.label)






```

As single row

```{r}


df.newplot <- dfp.tall

df.melt <- melt(df.newplot, id.vars = "sample.id")

variables <- c("has.all.slides",
               "has.circle.combo",
               "has.star.combo",
               "is.low.consensus",
               "is.middle.consensus",
               "is.high.consensus",
               "is.high.and.low",
               "is.low.and.middle",
               "is.high.and.middle")

# format for plot
df.plot <- df.melt[df.melt$variable %in% variables,]
df.plot[is.na(df.plot$value),]$value <- "NA"
df.plot$variable <- factor(df.plot$variable, levels = variables)

# new plot object
new.plot <- ggplot(df.plot, 
                   aes(x = sample.id, y = variable, fill = value)) +
  geom_tile(color = "black") + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

new.plot
```

# Session info

```{r}
sessionInfo()
```
