---
title: "01_run"
author: "Sean Maden"
date: "2023-10-02"
output: html_document
---

```{r setup, include=FALSE}

libv <- c("ggplot2")
sapply(libv, library, character.only = TRUE)


knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
load("./env/09_quality/01_run_script.RData")


```

# High neuron proportion

```{r, include=TRUE}


sample.id.iter.high <- "Br3942_mid"

# DYNAMIC TITLE
varname <- "is.high.consensus"
dynamic.title <- paste0(
  
  "S_pseudobulk id :", sample.id.iter.high, "; ",
  "varname_facet: ", varname
  
)

# new plot object
new.plot.experiment.high <- 
  ggplot(dfp.tall.high, 
         aes(x = neuron.true, 
             y = neuron.pred, 
             color = sample.id, 
             size = matched.id)) + 
  geom_point() + 
  geom_abline(slope = 1, intercept = 0) + 
  facet_wrap(~type) +
  ggtitle(dynamic.title) +
  facet_wrap(~is.high.consensus*type, ncol=2)

# evaluate the object, getting plot as side effect
new.plot.experiment.high
```

Save formatted plot.

```{r}
new.plot.filename <- "fig3a.jpg"
new.plot.path <- file.path("figures", "03_shuffle", new.plot.filename)
###
new.plot.high.save <- ggplot(dfp.tall.high, 
                            aes(x = neuron.true, y = neuron.pred, 
                                shape = matched.id)) + 
  geom_point(size = 5, alpha = 0.5, colour = point.color) + 
  geom_abline(slope = 1, intercept = 0) + 
  facet_wrap(~type) + theme_bw() +
  ggtitle(paste0("S pseudobulk id: ", sample.id.iter.high)) + 
  xlim(0.2, 1) + ylim(0.2, 1)
###
new.plot.high.save
```

Save

```{r}
```

# Session info

```{r}
sessionInfo()
```