---
title: "02_crossvalidate"
author: "Sean Maden"
date: "2023-09-19"
output:
  pdf_document: default
  html_document: default
---
```{r}
knitr::opts_chunk$set(fig.width=10, fig.height=10, echo = F)
libv <- c("ggplot2")
sapply(libv, library, character.only = T)
```

```{r setup, include=FALSE}
setwd("..")
setwd("..")
load("./env/05_bulk/02_crossvalidate_script.RData")
```
 
```{r}

dfp <- df.k2
# format plot data
dfp <- dfp[dfp$crossvalidation=="validation",]
dfp[dfp$s.set.label=="s.null",]$s.set.label <- "unscaled"
dfp[dfp$s.set.label=="s.manual",]$s.set.label <- "scaled"
dfp$experiment.type <- paste0("z_type : ", dfp$experiment.type)

dfp$bulk.sample.id <- gsub("c1", "c", dfp$bulk.sample.id)
dfp$bulk.sample.id <- gsub("k1", "k", dfp$bulk.sample.id)
dfp$bulk.sample.id <- gsub("o1", "o", dfp$bulk.sample.id)
# experiment conditions
dfp$bulk.sample.condition <- cd[dfp$bulk.sample.id,]$expt_condition
table(dfp$bulk.sample.condition)

dfp <- na.omit(dfp)

```
 
# Supplemental Figure : Scatterplot of true and predicted proportions across experiments

```{r}

new.plot.scatter <- ggplot(dfp, aes(x = true.neuron, y = neuron)) + 
  theme_bw() + geom_point(alpha = 0.5) + 
  geom_abline(slope = 1, intercept = 0) + 
  facet_grid(s.set.label~experiment.type) + xlab("Known") + 
  ylab("Predicted") + xlim(0, 1) + ylim(0, 1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

new.plot.scatter

```

```{r}
setwd("..")
setwd("..")

new.plot.path <- "./figures/05_bulk/figs2b_validate.jpg"
jpeg(new.plot.path, width = 4.5, height = 5, units = "in", res = 400)
new.plot.scatter
dev.off()
```

# Supplemental Figure : Neuron errors across conditions by cross validation set, experiment

```{r}

new.plot.jitterbox <- ggplot(df.k2, aes(x = experiment.type, y = abs.error.neuron)) + 
  geom_jitter(alpha = 0.5) + geom_boxplot(alpha = 0, color = "cyan") +
  facet_wrap(~crossvalidation) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("z_type") + ylab("Error (neuron)")

new.plot.jitterbox

```

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/05_bulk/figs3e_experimenttype.jpg"

jpeg(new.plot.path, width = 4, height = 3, units = "in", res = 400)
new.plot.jitterbox
dev.off()

```

# Supplemental Figures: Quantile boxplots and jittered points by conditions

```{r}

# Filter results to within-reference condition only
dfp <- df.k2[df.k2$experiment.type=="shared.reference",]
dfp$preparation.type <- gsub(".*_", "", dfp$bulk.sample.condition)
dfp <- na.omit(dfp)

```

```{r}
# combine all samples
new.plot.jitter.prep <- ggplot(dfp, aes(x = preparation.type, y = abs.error.neuron)) + 
  geom_jitter(alpha = 0.3) + geom_boxplot(alpha = 0, color = "cyan") + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Error (neuron)") + xlab("Preparation type")
new.plot.jitter.prep

```

```{r}
setwd("..")
setwd("..")
setwd("..")
# RMSE
source("./software/src/rmse.R")

propRMSE <- data.frame(
  glial_predicted = dfp$glial,
  neuron_predicted = dfp$neuron,
  glial_known = as.numeric(dfp$true.glial),
  neuron_known = dfp$true.neuron,
  sample.id = dfp$preparation.type,
  condition.id = dfp$bulk.scale.type,
  replicate.id = dfp$crossvalidation
)

#rmseNew <- applyRmse(propRMSE, cellTypesVector = c("neuron", "glial"))
#rmseNew$returnRmseTall

# manual
propRMSEall <- propRMSE
propRMSE <- propRMSEall[propRMSEall$sample.id=="polyA",]
errorVector <- propRMSE$glial_predicted-propRMSE$glial_known
errorVector <- c(errorVector, propRMSE$neuron_predicted-propRMSE$neuron_known)
errorSq <- errorVector^2
meanErr <- sum(errorSq)/length(errorSq)
rmsePolyA <- sqrt(meanErr)
rmsePolyA

propRMSE <- propRMSEall[propRMSEall$sample.id=="RiboZeroGold",]
errorVector <- propRMSE$glial_predicted-propRMSE$glial_known
errorVector <- c(errorVector, propRMSE$neuron_predicted-propRMSE$neuron_known)
errorSq <- errorVector^2
meanErr <- sum(errorSq)/length(errorSq)
rmseRZG <- sqrt(meanErr)
rmseRZG


```

```{r}
setwd("..")
setwd("..")

new.plot.path <- "./figures/05_bulk/figs3c_library_condition_allsamples.jpg"
jpeg(new.plot.path, width = 4, height = 3, units = "in", res = 400)
new.plot.jitter.prep
dev.off()
```

```{r}
# combined samples
dfp$cell_compartment <- gsub("_.*", "", dfp$bulk.sample.condition)
new.plot.jitter.compart <- ggplot(dfp, aes(x = cell_compartment, y = abs.error.neuron)) + 
  geom_jitter(alpha = 0.3) + geom_boxplot(alpha = 0, color = "cyan") + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Error (Neuron)") + xlab("Cell compartment")

new.plot.jitter.compart

```

```{r}
setwd("..")
setwd("..")

new.plot.path <- "./figures/05_bulk/figs3d_cell_compartment_allsamples.jpg"
jpeg(new.plot.path, width = 4, height = 3, units = "in", res = 400)
new.plot.jitter.compart
dev.off()
```

# Session info

```{r}
sessionInfo()
```