---
title: "02_crossvalidate"
author: "Sean Maden"
date: "2023-09-19"
output:
  pdf_document: default
  html_document: default
---
```{r}
knitr::opts_chunk$set(fig.width=10, fig.height=10)
libv <- c("ggplot2")
sapply(libv, library, character.only = T)
```

```{r setup, include=FALSE}
setwd("..")
setwd("..")
load("./env/05_bulk/02_crossvalidate_script.RData")
```
 
# Figure S2B -- scatterplot

```{r}
df.k2.filt <- df.k2[df.k2$crossvalidation=="validation",]
df.k2.filt[df.k2.filt$s.set.label=="s.set1",]$s.set.label <- "unscaled"
df.k2.filt[df.k2.filt$s.set.label=="s.set4",]$s.set.label <- "scaled"

new.plot.scatter <- ggplot(df.k2.filt, aes(x = true.neuron, y = neuron)) + 
  theme_bw() + geom_point(alpha = 0.5) + geom_abline(slope = 1, intercept = 0) + 
  facet_wrap(~s.set.label)

new.plot.scatter
```

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/05_bulk/figs2b_validate.jpg"
jpeg(new.plot.path, width = 4, height = 3, units = "in", res = 400)
new.plot.scatter
dev.off()
```

# Figure S3A

```{r}
new.plot.jitterbox <- ggplot(df.k2, aes(x = experiment.type, y = abs.error.neuron)) + 
  geom_jitter(alpha = 0.5) + geom_boxplot(alpha = 0, color = "cyan") +
  facet_wrap(~crossvalidation) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
new.plot.jitterbox
```

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/05_bulk/figs3a_experimenttype.jpg"
jpeg(new.plot.path, width = 4, height = 3, units = "in", res = 400)
new.plot.jitterbox
dev.off()
```

# Filter results to within-reference condition only

```{r}
df.k2 <- df.k2[df.k2$experiment.type=="within.reference",]
```

# Figure S3B

```{r}
df.k2$preparation.type <- gsub(".*_", "", df.k2$bulk.sample.condition)
df.k2 <- na.omit(df.k2)
new.plot.jitter.prep <- ggplot(df.k2, aes(x = preparation.type, y = abs.error.neuron)) + 
  geom_jitter(alpha = 0.3) + geom_boxplot(alpha = 0, color = "cyan") + theme_bw() +
  facet_wrap(~crossvalidation) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
new.plot.jitter.prep
```

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/05_bulk/figs3b_preparation.jpg"
jpeg(new.plot.path, width = 4, height = 3, units = "in", res = 400)
new.plot.jitter.prep
dev.off()
```

# Figure S3B

```{r}
df.k2$cell_compartment <- gsub("_.*", "", df.k2$bulk.sample.condition)
new.plot.jitter.compart <- ggplot(df.k2, aes(x = cell_compartment, y = abs.error.neuron)) + 
  geom_jitter(alpha = 0.3) + geom_boxplot(alpha = 0, color = "cyan") + theme_bw() +
  facet_wrap(~crossvalidation) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
new.plot.jitter.compart
```

```{r}
setwd("..")
setwd("..")
new.plot.path <- "./figures/05_bulk/figs3c_compartment.jpg"
jpeg(new.plot.path, width = 4, height = 3, units = "in", res = 400)
new.plot.jitter.compart
dev.off()
```

# Session info

```{r}
sessionInfo()
```