---
title: "RMSE ABIS-seq results"
author: "Sean Maden"
date: "2023-10-24"
output:
  pdf_document: default
  html_document: default
---

This notebook compares the RMSE across S13 samples for each cell type, using the
flow cytometry proportions as true cell proportions.

```{r setup, include=FALSE}
libv <- c("ggplot2", "gridExtra")
sapply(libv, library, character.only = TRUE)
knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
load("./env/02_abisseq/03_rmse_script.RData")
```

# Summaries

## RMSE calculations

```{r}
knitr::kable(df.rmse.wide)
```

## RMSE summaries

# Plots

## RMSE

```{r}
ggplot(df.rmse.wide, aes(x = rmse.unscaled, y = rmse.scaled,
                         color = cell.type, size = s.cell.size)) + 
  geom_point() + geom_abline(slope = 1, intercept = 0)
```

## Pearson R coefficients

```{r}
ggplot(df.rmse.wide, aes(x = pearson.r.unscaled, y = pearson.r.scaled,
                         color = cell.type, size = s.cell.size)) + 
  geom_point() + geom_abline(slope = 1, intercept = 0)
```

## RMSE difference versus Pearson R difference

```{r}
df.rmse.wide$rmse.diff = df.rmse.wide$rmse.scaled=df.rmse.wide$rmse.unscaled
df.rmse.wide$pearson.r.diff = df.rmse.wide$pearson.r.scaled-df.rmse.wide$pearson.r.unscaled

ggplot(df.rmse.wide, aes(x = rmse.diff, y = pearson.r.diff,
                         color = cell.type, size = s.cell.size)) + 
  geom_point() + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) +
  xlab("RMSE difference (Scaled - Unscaled)") +
  ylab("Pearson R difference (Scaled - Unscaled)")
```

# Conclusions

# Session info

```{r}
sessionInfo()
```
