---
title: "Pseudobulk k3 with and without cell size rescaling, cohort2"
author: "Sean Maden"
date: "2023-10-10"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
libv <- c("ggplot2")
sapply(libv, library, character.only = TRUE)
knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
list.files()
load("./env/01_pseudobulk/01_k3_mrb_script.RData")
```

# Figure S2C

Facet grid (3x2) for Ecit, Inhib, glial, scaled and unscaled.

```{r}
dfp1 <- data.frame(
  known = dfp.tall$Excit.true,
  pred = dfp.tall$Excit.pred,
  type = dfp.tall$type,
  celltype = rep('Excit', nrow(dfp.tall))
)
dfp2 <- data.frame(
  known = dfp.tall$Inhib.true,
  pred = dfp.tall$Inhib.pred,
  type = dfp.tall$type,
  celltype = rep('Inhib', nrow(dfp.tall))
)
dfp3 <- data.frame(
  known = dfp.tall$glial.true,
  pred = dfp.tall$glial.pred,
  type = dfp.tall$type,
  celltype = rep('glial', nrow(dfp.tall))
)
dfp <- rbind(dfp1, rbind(dfp2, dfp3)) |> as.data.frame()

dfp$celltype <- 
  factor(dfp$celltype, levels = c("Excit", "Inhib", "glial"))

newScatterGrid <- ggplot(dfp, aes(x = known, y = pred)) +
  geom_point() + geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + geom_vline(xintercept = 0.5) +
  facet_grid(celltype~type) + theme_bw() +
  xlab("Known") + ylab("Predicted") +
  xlim(0,1) + ylim(0,1) + ggtitle("Tran et. al. 2021")

newScatterGrid
```

# Figure S2B

Errors boxplots, glial and neuron.

```{r}
dfp$error <- abs(dfp$known-dfp$pred)
newBoxGrid <- ggplot(dfp, aes(x = type, y = error)) +
  geom_jitter(alpha = 0.5) + 
  geom_boxplot(color = "cyan", alpha = 0) + theme_bw() +
  facet_grid(~celltype) + theme_bw() + ylab("Error") +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.x = element_blank())
newBoxGrid
```

# Scatterplots

Show

```{r}
# plot proportions multipanel -- scale vs with scale
new.plot <- ggplot(dfp.ct, aes(x = true.noscale, y = pred.noscale)) + 
  geom_point(size = 4, alpha = 0.5) + 
  geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + geom_vline(xintercept = 0.5) + theme_bw() +
  xlab("Known") + ylab("Predicted") +
  xlim(0, 1) + ylim(0, 1) + facet_wrap(~celltype) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Save

```{r}
setwd("..")
setwd("..")
new.plot.name <- "fig2d_cohort2.jpg"
jpeg(file.path("./figures/01_pseudobulk/", new.plot.name), 
     width = 5.5, height = 2.5, units = "in", res = 400)
new.plot
dev.off()
```

# Figure S1F, boxplots

Show

```{r}
# jitterbox -- jittered points and boxplots of absolute errors
dfp.ae1 <- data.frame(celltype = dfp.ct$celltype,
                      abs.error = dfp.ct$abs.error.withscale)
dfp.ae1$type <- "withscale"
dfp.ae2 <- data.frame(celltype = dfp.ct$celltype,
                      abs.error = dfp.ct$abs.error.noscale)
dfp.ae2$type <- "noscale"
dfp.ae <- rbind(dfp.ae1, dfp.ae2)

new.plot <- ggplot(dfp.ae, aes(x = celltype, y = abs.error)) + 
  geom_jitter(alpha = 0.5, size = 2.5) + 
  geom_boxplot(color = "cyan", alpha = 0) + theme_bw() + facet_wrap(~type) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Error")

```

Save

```{r}
setwd("..")
setwd("..")
new.plot.name <- "figs1f_cohort2.jpg"
jpeg(file.path("./figures/01_pseudobulk/", new.plot.name), 
     width = 4.5, height = 2.5, units = "in", res = 400)
new.plot
dev.off()
```
```


# Session info

```{r}
sessionInfo()
```