---
title: "Cell type proportion summaries"
author: "Sean Maden"
date: "2023-09-21"
output:
  pdf_document: default
  html_document: default
---

Cell type proportions from snRNAseq and RNAscope.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libv <- c("dplyr", "ggplot2", "GGally", "ggcorrplot")
sapply(libv, library, character.only = TRUE)
```

```{r}
setwd("..")
setwd("..")
load("./env/08_sizes/01_run_script.RData")
dfp.wide <- list.dfp$dfp.wide
dfp.tall <- list.dfp$dfp.tall
```
# Correlations

```{r}
df.cor <- dfp.wide[,c("sn.neuron", "rn.neuron", "br.region", "subject.id")]

df.region <- 
  aggregate(df.cor, by = list(br.region=df.cor$br.region), FUN = median)

df.sample <- 
  aggregate(df.cor, by = list(subject.id=df.cor$subject.id), FUN = median)

ggcorrplot(cor(df.region[,c("sn.neuron", "rn.neuron")]))
ggcorrplot(cor(df.sample[,c("sn.neuron", "rn.neuron")]))
```

# Plots

```{r}
ggpairs(dfp.wide[,c("sn.neuron", "rn.neuron")])
```

```{r}
ggplot(dfp.tall, aes(x = subject.id, y = neuron)) + 
  geom_jitter() + geom_boxplot(alpha = 0, color = "cyan") + facet_wrap(~size.type.label) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(dfp.tall, aes(x = br.region, y = neuron)) + 
  geom_jitter() + geom_boxplot(alpha = 0, color = "cyan") + facet_wrap(~size.type.label) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ratio.yintercept.ref = 1
```

```{r}
ggplot(dfp.tall, aes(x = br.region, y = ratio.glial.neuron)) + 
  geom_jitter() + geom_boxplot(alpha = 0, color = "cyan") + facet_wrap(~size.type.label) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_hline(yintercept = ratio.yintercept.ref)
```

```{r}
new.plot1 <- ggplot(dfp.tall, aes(x = br.region, y = ratio.neuron.glial)) + 
  geom_jitter() + geom_boxplot(alpha = 0, color = "cyan") + facet_wrap(~size.type.label) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_hline(yintercept = ratio.yintercept.ref)
new.plot1
```

# Save

```{r}
setwd("..")
setwd("..")
list.files()
new.plot.path <- "./figures/08_sizes/supplemental_figure_boxplots_ratio_neuron_glial.jpg"
jpeg(new.plot.path, width = 5, height = 3, res = 400, units = "in")
new.plot1
dev.off()
```

# Session info

```{r}
sessionInfo()
```
