---
title: "mrb-donordf-pca"
author: "Sean Maden"
date: "2023-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libv <- c("lute", "ggpubr", "gridExtra", "ggrepel",
          "SingleCellExperiment", "SummarizedExperiment",
          "glmGamPoi")
sapply(libv, library, character.only = TRUE)

# manage paths
# source and save paths
code.dname <- "08_lute-simulations"
proj.dname <- "deconvo_method-paper"
save.dpath <- file.path(proj.dname, "outputs", code.dname)
source.dpath <- file.path(proj.dname, "source")

# load scef
scef.fname <- "scef-mrb_gmr2-k2-t20_dlpfc.rda"
scef <- get(load(file.path(save.dpath, scef.fname)))

```

Make `donor.data.frame` from `logcounts`.

```{r}
mexpr <- assays(scef)$logcounts
mexpr <- as.matrix(mexpr)
ddf <- donordf_from_mexpr(mexpr = mexpr, typev.rd = NULL,
                          groupv.cd = scef$donor, typev.cd = scef$k2, verbose = T)
ddf.fname <- "donordf_logcounts-k2_mrb-dlpfc.rda"
save(ddf, file = file.path(save.dpath, ddf.fname))
```

Run donor bias expt.

```{r}
lexpr <- run_donor_bias_expt(ddf)
```
