---
title: "Pseudobulk k2 with and without cell size rescaling, cohort1"
author: "Sean Maden"
date: "2023-09-17"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
libv <- c("ggplot2")
sapply(libv, library, character.only = TRUE)
knitr::opts_chunk$set(echo = TRUE)
setwd("..")
setwd("..")
list.files()
load("./env/02_pseudobulk/01_k2.RData")
```

# Plot neuron proportions

Neuron

```{r}
summary(dfp.ct[dfp.ct$celltype=="neuron",]$abs.error.noscale)
sd(dfp.ct[dfp.ct$celltype=="neuron",]$abs.error.noscale)

summary(dfp.ct[dfp.ct$celltype=="neuron",]$abs.error.withscale)
sd(dfp.ct[dfp.ct$celltype=="neuron",]$abs.error.withscale)
```

# Figure 2A

View

```{r}
# plot proportions panel -- no scale
new.plot <- ggplot(dfp.tall[dfp.tall$type=="noscale",], 
       aes(x = neuron.true, y = neuron.pred)) + 
  geom_point(size = 4, alpha = 0.5) + 
  geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + geom_vline(xintercept = 0.5) + theme_bw() +
  xlab("Known") + ylab("Predicted") +
  xlim(0, 1) + ylim(0, 1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

# Figure S1B

```{r}
new.plot <- ggplot(dfp.tall, aes(x = neuron.true, y = neuron.pred)) + 
  geom_point(size = 4, alpha = 0.5) + 
  geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + geom_vline(xintercept = 0.5) + theme_bw() +
  xlab("Known") + ylab("Predicted") +
  xlim(0, 1) + ylim(0, 1) + facet_wrap(~type) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
new.plot
```

```{r}
setwd("..")
setwd("..")
new.plot.name <- "figs1b_cohort1.jpg"
jpeg(file.path("./figures/02_pseudobulk/", new.plot.name), 
     width = 4, height = 2.5, units = "in", res = 400)
new.plot
dev.off()
```

# Figure S1A

Proportions multipanel (2x2), glial and neuron.

```{r}
dfp1 <- data.frame(
  known = dfp.tall$neuron.true,
  pred = dfp.tall$neuron.pred,
  type = dfp.tall$type,
  celltype = rep('neuron', nrow(dfp.tall))
)
dfp2 <- data.frame(
  known = dfp.tall$glial.true,
  pred = dfp.tall$glial.pred,
  type = dfp.tall$type,
  celltype = rep('glial', nrow(dfp.tall))
)
dfp <- rbind(dfp1, dfp2) |> as.data.frame()

newScatterGrid <- ggplot(dfp, aes(x = known, y = pred)) +
  geom_point() + geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + geom_vline(xintercept = 0.5) +
  facet_grid(type~celltype) + theme_bw() +
  xlab("Known") + ylab("Predicted")
```

# Figure S1B

Errors boxplots, glial and neuron.

```{r}
dfp$error <- abs(dfp$known-dfp$pred)
newBoxGrid <- ggplot(dfp, aes(x = type, y = error)) +
  geom_jitter(alpha = 0.5) + 
  geom_boxplot(color = "cyan", alpha = 0) + theme_bw() +
  facet_grid(~celltype) + theme_bw()
```

# Further K2 plots

```{r}
# make new plots
# plot proportions panel -- no scale
ggplot(dfp.tall[dfp.tall$type=="noscale",], 
       aes(x = neuron.true, y = neuron.pred)) + geom_point() + 
  geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + geom_vline(xintercept = 0.5) + theme_bw() +
  xlab("True proportion") + ylab("Predicted proportion") +
  xlim(0, 1) + ylim(0, 1) + ggtitle("Neuron")

# plot proportions multipanel -- scale vs with scale
ggplot(dfp.tall, aes(x = neuron.true, y = neuron.pred)) + geom_point() + 
  geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + geom_vline(xintercept = 0.5) + theme_bw() +
  xlab("True proportion") + ylab("Predicted proportion") +
  xlim(0, 1) + ylim(0, 1) + facet_wrap(~type) + ggtitle("Neuron")

# jitterbox -- jittered points and boxplots of absolute errors
ggplot(dfp.tall, aes(x = type, y = neuron.abs.error)) + geom_jitter(alpha = 0.5) + 
  geom_boxplot(color = "cyan", alpha = 0) + theme_bw() + ggtitle("Neuron")
```

```{r}
setwd("..")
setwd("..")
new.plot.name <- "figs1a_cohort1.jpg"
jpeg(file.path("./figures/02_pseudobulk/", new.plot.name), 
     width = 3, height = 3, units = "in", res = 400)
new.plot
dev.off()
```

# Scatterplots with 2 cell types from K2 results

Make plot from pseudobulk results.

```{r}
dfi <- dfp.tall
dfi1 <- data.frame(
  true = dfi$neuron.true,
  pred = dfi$neuron.pred,
  sample.id = dfi$sample.id,
  type = dfi$type,
  celltype = "neuron"
)
dfi2 <- data.frame(
  true = dfi$glial.true,
  pred = dfi$glial.pred,
  sample.id = dfi$sample.id,
  type = dfi$type,
  celltype = "glial"
)
dfp <- rbind(dfi1, dfi2) |> as.data.frame()
```

Preview plots.

```{r}
cellTypeColor1 <- "blue"
cellTypeColor2 <- "red"
idLineColor <- "orange"

# get plot objects
new.plot.k2.noline <- ggplot(dfp, 
                   aes(x = true, y = pred, colour = celltype)) + 
  geom_point(size = 4, alpha = 0.3) + 
  geom_abline(slope = 1, intercept = 0) + 
  geom_hline(yintercept = 0.5) + 
  geom_vline(xintercept = 0.5) + theme_bw() +
  xlab("Known") + ylab("Predicted") +
  xlim(0, 1) + ylim(0, 1) + facet_wrap(~type) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = c(cellTypeColor2, cellTypeColor1))
new.plot.k2.withline <-
  new.plot.k2.noline + geom_line(aes(group=sample.id), color = idLineColor)

new.plot.k2.noline
new.plot.k2.withline
```

```{r}
new.plot.k2.noline + facet_grid(celltype~type)

setwd("..")
setwd("..")
jpeg("./figures/02_pseudobulk/fig2_dlpfc-k2-result-facet.jpg", 
     width = 6.5, height = 5.5, units = "in", res = 400)
new.plot.k2.noline + facet_grid(celltype~type)
dev.off()
```

Save to JPEG.

```{r}
setwd("..")
setwd("..")
jpeg("./figures/02_pseudobulk/fig2_dlpfc-k2-result-withline.jpg", 
     width = 6.5, height = 3, units = "in", res = 400)
new.plot.k2.withline
dev.off()
```

# Session info

```{r}
sessionInfo()
```