---
title: "Real bulk results"
author: "Sean Maden"
date: "2023-09-21"
output:
  pdf_document: default
  html_document: default
---

Deconvolution on real bulk samples.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libv <- c("dplyr", "ggplot2", "GGally", "gridExtra")
sapply(libv, library, character.only = TRUE)
```

```{r}
setwd("..")
setwd("..")
load("./env/07_adjustment/03_run_adjustment_realbulk_all_script.RData")
list.df.true <- metadata(sce)[["list.df.true.k2"]]
plotsList <- function(dfp){
  # plotsList
  # 
  # scatterplot and jitterbox plot of results data, with outlier label.
  #
  # dfp.tall results data.frame
  #
  #
dfp$scale <- ifelse(dfp$scale, "withscale", "noscale")

dfLabel <- dfp[dfp$true < 0.75 & dfp$value < 0.25,]

new.plot.tall <- ggplot(dfp, aes(x = true, y = value)) + 
  geom_point(size = 4, alpha = 0.5) + geom_abline(slope = 1, intercept = 0) + facet_wrap(~scale) + 
  xlab("Known") + ylab("Predicted") + xlim(0.1,0.9) + ylim(0.1,0.9) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(data = dfLabel, aes(x = true, y = value), 
            label = sample.id, nudge_x = 0.1, nudge_y = 0.1)
new.plot.tall

new.plot.tall.jitterbox <- ggplot(dfp, aes(x = scale, y = error)) + 
  geom_jitter(alpha = 0.5, width = 0.5, height = 0) + theme_bw() +
  geom_boxplot(alpha = 0, color = "cyan") + 
  xlab("Scale") + ylab("Error (neuron)") + ylim(0, 0.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank())
new.plot.tall.jitterbox
return(list(
  new.plot.tall, new.plot.tall.jitterbox
))
}
```

```{r}
list.df.true <- metadata(sce)[["list.df.true.k2"]]

for(sample.id in unique(dfp.tall$sample.id)){
  message(sample.id)
  message(identical(dfp.tall[dfp.tall$sample.id==sample.id,]$true[1],
            as.numeric(list.df.true[[sample.id]]["neuron"])))
}
```
  
```{r}
for(sample.id in unique(dfp.tall$sample.id)){
  filter.dfp.tall <- dfp.tall$sample.id==sample.id
  filter.dfp.wide <- rownames(dfp.wide)==sample.id
  true.neuron.value <- as.numeric(df.true.list[[sample.id]]["neuron"])
  dfp.tall[filter.dfp.tall,]$true <- true.neuron.value
  dfp.wide[filter.dfp.wide,]$neuron.true <- true.neuron.value
}
dfp.tall$error <- abs(dfp.tall$true-dfp.tall$value)
```

# Plots

```{r}
ggpairs(dfp.wide, 
        columns = rev(colnames(dfp.wide)),
        xlim = c(0, 1), ylim = c(0, 1))
```

```{r}
new.plot.tall <- ggplot(dfp.tall, aes(x = true, y = value, color = sample.id)) + 
  geom_point() + geom_abline(slope = 1, intercept = 0) + 
  facet_wrap(~scale*algorithm) + xlab("True") + 
  ylab("Predicted") + xlim(0.1,0.9) + ylim(0.1,0.9) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
new.plot.tall
```

```{r}
new.plot.tall.jitterbox <- ggplot(dfp.tall, 
                                  aes(x = scale, y = error)) + 
  geom_jitter(alpha = 0.5, width = 0.5, height = 0) + geom_boxplot(alpha = 0, color = "cyan") +
  facet_wrap(~algorithm) + xlab("Scale") + 
  ylab("Error (neuron)") + ylim(0, 0.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
new.plot.tall.jitterbox
```

## Multipanel scatterplots and jitterplots, neuron and glial

```{r}
# append glial
dfp.tall2 <- dfp.tall
dfp.tall2$cell.type <- "glial"
dfp.tall2$value <- 1-dfp.tall2$value
dfp.tall2$true <- 1-dfp.tall2$true
dfp.tall <- rbind(dfp.tall, dfp.tall2) |> as.data.frame()

plotsList <- function(dfp, outlier = TRUE){
    # plotsList
    # 
    # scatterplot and jitterbox plot of results data, with outlier label.
    #
    # dfp.tall results data.frame
    #
    #
    #
    #
  
    
    dfp$scale <- ifelse(dfp$scale, "withscale", "noscale")
    
    newPlot <- ggplot(dfp, aes(x = true, y = value)) + 
      geom_point(size = 4, alpha = 0.5) + 
      geom_abline(slope = 1, intercept = 0) + 
      facet_grid(cell.type~scale) + xlab("Known") + 
      ylab("Predicted") + theme_bw() + xlim(0, 1) + ylim(0, 1) +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
        
    if(outlier){
      dfLabelGlial <- dfp[dfp$value > 0.75 & dfp$cell.type == "glial",]
      dfLabelNeuron <- dfp[dfp$value < 0.25 & 
                             dfp$true < 0.75 & dfp$cell.type == "neuron",]
    newPlot <- newPlot +
      geom_text(data = dfLabelNeuron, aes(x = true, y = value), 
                  label = sample.id, nudge_x = 0.1, nudge_y = 0.1) +
      geom_text(data = dfLabelGlial, aes(x = true, y = value), 
                  label = sample.id, nudge_x = 0.1, nudge_y = 0.1)
    }
    
    
    
      
    jitterbox <- ggplot(dfp[dfp$cell.type == "neuron",], aes(x = scale, y = error)) + 
        geom_jitter(alpha = 0.5, width = 0.5, height = 0) + theme_bw() +
        geom_boxplot(alpha = 0, color = "cyan") + 
        xlab("Scale") + ylab("Error") + ylim(0, 0.5) +
        theme(axis.text.x = element_text(angle = 45, hjust = 1),
              axis.title.x = element_blank())
    
    return(list(
        newPlot, jitterbox
    ))
}

plotsListNNLS <- plotsList(dfp.tall[dfp.tall$algorithm=="nnls",])
plotsListMUSIC <- plotsList(dfp.tall[dfp.tall$algorithm=="music",])
plotsListBISQUE <- plotsList(dfp.tall[dfp.tall$algorithm=="bisque",], outlier = FALSE)

```

# Save

Save NNLS multipanel plot.

```{r}
setwd("..")
setwd("..")

jpeg("./figures/07_adjustment/fig3_bulk-results_nnls.jpg", 
     width = 6, height = 4, units = "in", res = 400)

grid.arrange(plotsListNNLS[[1]], plotsListNNLS[[2]],  
             layout_matrix = matrix(c(1,1,2), byrow=TRUE, nrow = 1))

dev.off()

```

Save Bisque and MuSiC multipanel plot.

```{r}
setwd("..")
setwd("..")
jpeg("./figures/07_adjustment/fig3_bulk-results_music-bisque.jpg", 
     width = 5.5, height = 8, units = "in", res = 400)
grid.arrange(plotsListMUSIC[[1]] + ggtitle("MuSiC"), plotsListMUSIC[[2]] + ggtitle(""), 
             plotsListBISQUE[[1]] + ggtitle("Bisque"), plotsListBISQUE[[2]] + ggtitle(""), 
             layout_matrix = matrix(c(1,1,2,3,3,4), byrow = TRUE, nrow = 2))
dev.off()

```

Save ggpairs plot.

```{r}
jpeg("./figures/07_adjustment/figs12_ggpairs_realbulk.jpg", 
     width = 10, height = 10, units = "in", res = 400)

ggpairs(dfp.wide, 
        columns = rev(colnames(dfp.wide)),
        xlim = c(0, 1), ylim = c(0, 1))

dev.off()
```

# Session info

```{r}
sessionInfo()
```
