---
title: "04_scale-pb-expt"
author: "Sean Maden"
date: '2022-10-13'
output: html_document
---

This vignette times the lpb function by sampling cells from sef, where 
sef represents data from a real (non-simulated) snRNAseq experiment.

```{r setup, include=FALSE}
library(here)
# library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
message("here: ", here())
proj.dpath <- "deconvo_method-paper"
# source methods
source.dpath <- file.path("deconvo_method-paper",
                          "source")
source.fnv <- c("pb_methods", 
                "z_transformations")
for(fni in source.fnv){
  source(
    file.path(here(), 
              source.dpath, 
              paste0(fni, ".R")))}
lz.fname <- "lz_s-rescale-k4_dlpfc-ro1.rda"
lz.fpath <- file.path(proj.dpath, 
                      "outputs/03_test-stransform", 
                      lz.fname)
lz <- get(load(file.path(here(), lz.fpath)))
#dft <- data.frame(cell_type = c("Excit", "Inhib", "Oligo", "other"),
#                        mean = c(6, 8, 2, 2), 
#                        sd = c(2, 3, 1, 1))
#meanv <- c(6, 2, 2, 8)
#sdv <- c(2, 1, 1, 3)
#lz[["zs.stat"]] <- s_rescale(lz[["z.final"]], factorv = meanv)
#lz[["zs.rand"]] <- s_rescale(lz[["z.final"]], meanv = meanv, sdv = sdv)
sef.fname <- "sef-markers_ct-treg_stransform-expt_dlpfc-ro1.rda"
sef.fpath <- file.path(proj.dpath, 
                      "outputs/03_test-stransform", 
                      sef.fname)
sef <- get(load(file.path(here(), sef.fpath)))
#lexpt <- lz[c("z.final", "zs.stat", "zs.rand")]
```

# time run for n samples

Define a helper function to time the run.

```{r}
time_lpb_run <- function(nj, nk = 4, ng = 100, 
                         datv.str = c("c(sample(10, ","*",
                                      ", replace = T) + 1)")){
  # time_lpb_run
  #
  # example:
  # time_run(4)
  #
  #
  t1 <- Sys.time()
  datv = eval(parse(text = paste0(datv.str[1], nk, datv.str[2], nj, datv.str[3])))
  pb.expt <- get_pb_experiment(lz = lexpt, sef = sef, datv = datv, 
                      scale.range = 100:10000, ctvarname = "celltype.treg", 
                      plot.results = FALSE, method.str = "nnls", seed.num = 2)
  tdif <- Sys.time()-t1
  dfi <- data.frame(nj = nj, time = tdif)
  return(dfi)
}
```
```{r}
time_lpb_run(4)
```


Define a series of samples nj, and get the times for a series of nj values.

```{r}
njv <- seq(10)
tv <- do.call(rbind, 
              lapply(njv, 
                     function(nj){
                       time_lpb_run(nj)}))
```
```{r}
tv
```
# do log scale test

```{r}
njv <- c(1, 10, 100, 1000)
tv <- do.call(rbind, 
              lapply(njv, 
                     function(nj){
                       time_lpb_run(nj)}))
```

```{r}
tv
```