---
title: "06_minimal-example"
author: "Sean Maden"
date: '2022-10-17'
output: html_document
---

This vignette looks at a series of very small pseudobulking experiments to evaluate
how `nnls` performs under basic deconvolution conditions.

Source `pb_methods.R` functions.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
# library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
message("here: ", here())
proj.dpath <- "deconvo_method-paper"
# source methods
source.dpath <- file.path("deconvo_method-paper",
                          "source")
source.fnv <- c("pb_methods", 
                "z_transformations")
for(fni in source.fnv){
  source(
    file.path(here(), 
              source.dpath, 
              paste0(fni, ".R")))}
```

Define signature matrices. 

```{r}
lz <- get_exe_lz(cell.typev = c("typeA", "typeB"))
```

Define counts data and cell types.

```{r}
sef <- get_exe_sef(num.cells = 2, num.genes = 3, 
                   sample.num = 1, num.celltypes = 2)
sef[["celltypes"]] <- ifelse(sef[["celltypes"]]=="celltype1", 
                             "typeA", "typeB")
assays(sef)$counts[,1] <- c(1, 1, 10)
assays(sef)$counts[,2] <- c(10, 10, 1)
```

Do minimum pb experiment.

```{r}
datv <- c(10, 1)
lpb <- get_pb_experiment(lz, sef, datv, scale.range = 1, ctvarname = "celltypes",
                  plot.results = FALSE, method.str = "nnls", seed.num = 2)
```