---
title: "test_pb_nnls"
author: "Sean Maden"
date: '2022-10-10'
output: html_document
---

This notebook tests various properties of the pseudo-bulked experiment functions
as well as the strict deconvolution strategy.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# pseudo-bulk

```{r}
```

# nnls tests

```{r}
z.data <- matrix(sample(1000, 100), ncol = 5)
y.data <- matrix(sample(1000, 40), ncol = 2)
```

```{r}
pi.dati <- do.call(rbind, lapply(seq(ncol(z.data)), 
                                 function(i){
                                   nnls::nnls(y.data, 
                                              z.data[,i])$x}))
pi.dati
```

```{r}
nnls::nnls(y.data, t(z.data))
```

# glm tests

```{r}
library(glmnet)
```

predict single cell type.

```{r}
mod2 <- glmnet(y.data, z.data[,1], lambda = 0, lower.limits = 0, intercept = FALSE)
coef(mod2)
```

predict all cell types.

```{r}
mod <- do.call(cbind, lapply(seq(ncol(z.data)), function(ii){
  coef(glmnet(y.data, z.data[,ii], lambda = 0, lower.limits = 0, intercept = FALSE))
}))
mod
```

# bounded-variable least squares

```{r}
install.packages("bvls")
library(bvls)
```

get single cell type.

```{r}
mod3 <- bvls(y.data, z.data[,1], bl = rep(0, ncol(y.data)), bu = rep(Inf, ncol(y.data)))
```

get all cell types.

```{r}
mod <- do.call(cbind, lapply(seq(ncol(z.data)), function(ii){
  bvls(y.data, z.data[,ii], bl = rep(0, ncol(y.data)), bu = rep(Inf, ncol(y.data)))$x
}))
mod
```